daily:
  indie-mix:
    all_time_playlist: 2sadM6M9K9UqJvf2SFHHlu
    original_playlist: 37i9dQZF1EQqkOPvHGajmW
  house-mix:
    all_time_playlist: 0F9f5FhW0Lq60yQpYnv0Ql
    original_playlist: 37i9dQZF1EQpoj8u9Hn81e
    
weekly:
  daily-mix:
    all_time_playlist: 0lpfYyjSqOMsfZ8XxO0aa3
    original_playlist: 37i9dQZEVXcCwQg18md4qN
