name: spotify-archive

on:
  workflow_dispatch:
  schedule:
    # Weekly: Runs every Tuesday at 8 AM GMT+2
    - cron: "0 5 * * 2"
    # Daily: Runs everyday at 8 AM GMT+2
    - cron: "0 5 * * *"

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Archive daily
        if: contains(github.event.schedule, '0 5 * * *')
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          spotify-archive daily
      - name: Archive weekly
        if: contains(github.event.schedule, '0 5 * * 2')
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          spotify-archive weekly
